"""
ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
                                    ZZZZ
                                  ZZZZ
                                ZZZZ
                              ZZZZ
                            ZZZZ
                          ZZZZ
                        ZZZZ
                      ZZZZ
                    ZZZZ
                  ZZZZ
                ZZZZ
              ZZZZ
            ZZZZ
          ZZZZ
        ZZZZ
      ZZZZ
    ZZZZ
  ZZZZ
ZZZZ
ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
"""
"developed by Noon4ik"